version: "3"
services:

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_request"
      MYSQL_USER: "request"
      MYSQL_PASSWORD: "request"
    ports:
      - "3306:3306"
    restart: always